# Generated by Django 4.0.4 on 2022-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=160)),
                ('deadline', models.CharField(max_length=10)),
                ('progress', models.CharField(max_length=5)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
