# Generated by Django 4.0.4 on 2022-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='complete',
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
